Update id_test.yml

diff --git a/.github/workflows/id_test.yml b/.github/workflows/id_test.yml
--- a/.github/workflows/id_test.yml
+++ b/.github/workflows/id_test.yml
@@ -14,4 +14,12 @@ jobs:
       uses: actions/checkout@v2
 
     - name: Display Client ID
-      run: echo "Client ID: ${{ secrets.CLIENT_ID }}"
+      run: |
+        CLIENT_ID=${{ secrets.CLIENT_ID }}
+        echo "Client ID: $CLIENT_ID"
+        if [ "$CLIENT_ID" == "62038061756-ot0st3dqt1ekbec5mpbacra9t60k075r.apps.googleusercontent.com" ]; then
+          echo "Client ID is correct."
+        else
+          echo "Error: Client ID does not match the expected value."
+          exit 1
+        fi
